server:
  port: 8093


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test1?characterEncoding=utf-8
    username: root
    password: chen1213
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    # ??????? Thymeleaf ??????
    # ????? false ?????????????????????????
    # ?????????????????????
    cache: false

    # ?????????????????????
    # ??????????????????? /templates/???.html ??????
    prefix: classpath:/templates/
    suffix: .html

    encoding: utf-8
    # text/html???????????? text/html????????????? HTML ???
    servlet:
      content-type: text/html
    mode: HTML5

